
// This file is automatically generated by git.version.ts script
export const applicationversion = {
  version: '3.14.0',
  revision: '656d0f2',
  branch: 'main',
  date: 'Sun Mar 24 22:46:19 2024 +0100'
};