
// This file is automatically generated by git.version.ts script
export const applicationversion = {
  version: '3.0.2',
  revision: '781aadb',
  branch: 'main',
  date: 'Wed Mar 13 13:21:36 2024 +0100'
};