
// This file is automatically generated by git.version.ts script
export const applicationversion = {
  version: '3.5.0',
  revision: '7167b24',
  branch: 'main',
  date: 'Fri Mar 22 21:11:49 2024 +0100'
};